version: "3.7"

volumes:
  mongodb_data_dev:

networks:
  countly-dev:

services:
  mongodb:
    container_name: countly-mongodb
    image: 'bitnami/mongodb:6.0.8'
    volumes:
      - 'mongodb_data_dev:/bitnami'
    networks:
      countly-dev:

  countly-api:
    container_name: countly-api
    image: '1247537710/countly-api:latest'
    volumes:
      # - './log:/opt/countly/log'
      # - './uploads:/opt/countly/frontend/express/uploads'
    # Enterprise Edition: image: 'gcr.io/countly-01/api:20.11.2'
    environment:
      - COUNTLY_CONFIG__MAIL_TRANSPORT="nodemailer-smtp-transport"
      - COUNTLY_CONFIG__MAIL_CONFIG_HOST="smtp.qq.com"
      - COUNTLY_CONFIG__MAIL_CONFIG_PORT=465
      - COUNTLY_CONFIG__MAIL_CONFIG_AUTH_USER=""
      - COUNTLY_CONFIG__MAIL_CONFIG_AUTH_PASS=""
      - COUNTLY_CONFIG__MAIL_STRINGS_FROM="Countly Countly@qq.com"
      - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager
      # Enterprise Edition: - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,license,drill,funnels,retention_segments,flows,cohorts,surveys,remote-config,ab-testing,formulas,activity-map,concurrent_users,revenue,logger,systemlogs,populator,reports,crashes,push,geo,block,restrict,users,star-rating,slipping-away-users,compare,server-stats,assistant,dbviewer,crash_symbolication,crashes-jira,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,active_users,performance-monitoring,config-transfer,consolidate,data-manager,hooks,dashboards,sdk
      - COUNTLY_CONFIG__MONGODB_HOST=mongodb
      - NODE_OPTIONS="--max-old-space-size=2048"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 400s
    networks:
      countly-dev:
    depends_on:
      - mongodb

  countly-frontend:
    container_name: countly-frontend
    image: '1247537710/countly-frontend:latest'
    # Enterprise Edition: image: 'gcr.io/countly-01/frontend:20.11.2'
    environment:
      - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager
      # Enterprise Edition: - COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,license,drill,funnels,retention_segments,flows,cohorts,surveys,remote-config,ab-testing,formulas,activity-map,concurrent_users,revenue,logger,systemlogs,populator,reports,crashes,push,geo,block,restrict,users,star-rating,slipping-away-users,compare,server-stats,assistant,dbviewer,crash_symbolication,crashes-jira,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,active_users,performance-monitoring,config-transfer,consolidate,data-manager,hooks,dashboards,sdk
      - COUNTLY_CONFIG__MONGODB_HOST=mongodb
      - NODE_OPTIONS="--max-old-space-size=2048"
    networks:
      countly-dev:
    depends_on:
      - mongodb
    deploy:
      # There is usually no need in multiple frontends, so throttling down resources for it
      mode: global
      resources:
        limits:
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 400s

  nginx:
    container_name: countly-nginx
    image: 'bitnami/nginx'
    ports:
      - '8002:8080'
    volumes:
      - './bin/docker/nginx.server.conf:/opt/bitnami/nginx/conf/server_blocks/countly.conf:ro'
    networks:
      countly-dev:
    depends_on:
      - countly-api
      - countly-frontend
