version: "3.7"

volumes:
  mongodb_data:

networks:
  countly:

services:
  mongodb:
    image: 'bitnami/mongodb:6.0.8'
    volumes:
      - 'mongodb_data:/bitnami'
    ports:
      - '27017:27017'
    networks:
      countly: