version: "3.7"

volumes:
  countly_mongodb_data:

networks:
  countly:

services:
  mongodb:
    image: 'mongo:4.4.15'
    volumes:
      - 'countly_mongodb_data:/bitnami'
    ports:
      - '27017:27017'
    networks:
      countly: